title: DBHammer
description: 华东师范大学数据科学与工程学院
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://irisyou55.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 12
paginate_path: "/page/:num/"


sass:
  sass_dir: _sass
  style: compressed
